const CHUNK_PUBLIC_PATH = "server/app/search/page.js";
const runtime = require("../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_0962b827._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__fb250061._.js");
runtime.loadChunk("server/chunks/ssr/app_1f3630ef._.js");
runtime.loadChunk("server/chunks/ssr/_e0b4d99a._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_b07de5aa._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_c2f0b79c._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_forbidden-error_ea7ea172.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_unauthorized-error_c8949b27.js");
runtime.loadChunk("server/chunks/ssr/node_modules_node-fetch_src_index_587f51b6.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_eb2d1bd7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@genkit-ai_core_lib_b4b8dea8._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_zod_lib_9973ecc6._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_ajv_dist_e6327f72._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_zod-to-json-schema_dist_cfb46992._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_core_build_esm_ac2e01f7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_semantic-conventions_build_esm_17a93919._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_resources_build_esm_eadd61b9._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_sdk-metrics_build_esm_2bc910b7._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_sdk-trace-base_build_esm_ffb73884._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_protobufjs_c6ba58b0._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@opentelemetry_otlp-transformer_build_esm_7b4c78bd._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@grpc_grpc-js_cc2986af._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_handlebars_097a2825._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_yaml_dist_5cbea403._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_@genkit-ai_ai_lib_836f0c81._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_8cbda666._.js");
runtime.loadChunk("server/chunks/ssr/[root-of-the-server]__49593b33._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/search/page/actions.js { ACTIONS_MODULE0 => \"[project]/src/ai/flows/search-products.ts [app-rsc] (ecmascript)\" } [app-rsc] (server actions loader, ecmascript)", CHUNK_PUBLIC_PATH);
runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/search/page { METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico (static in ecmascript)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/app/search/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/search/page { METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico (static in ecmascript)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/forbidden-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/unauthorized-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_5 => \"[project]/app/search/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
