
import type { Product } from './types';

const products: Product[] = [
  {
    id: 1,
    name: 'Midnight Bloom',
    slug: 'midnight-bloom',
    description: 'An enigmatic and alluring fragrance that captures the essence of a moonlit garden. Perfect for evening wear.',
    price: 180,
    image: 'https://saeedghani.pk/cdn/shop/files/OudAlShams_300x.jpg?v=1750943020',
    category: 'Women',
    scentFamily: 'Floral',
    notes: {
      top: ['Jasmine', 'Tuberose'],
      middle: ['Ylang-Ylang', 'Orange Blossom'],
      base: ['Sandalwood', 'Musk'],
    },
    rating: 4.8,
    reviewCount: 124,
    reviews: [
      { id: '1', author: 'Eleanor', rating: 5, title: 'Absolutely Captivating!', comment: 'This is my new signature scent. It\'s dark, mysterious, and so elegant. I get compliments every time I wear it.', date: '2023-10-15' },
      { id: '2', author: 'Mark', rating: 4, title: 'A beautiful floral', comment: 'Bought this for my wife and she loves it. It\'s a very sophisticated and long-lasting floral fragrance.', date: '2023-09-22' }
    ]
  },
  {
    id: 2,
    name: 'Citrus Dawn',
    slug: 'citrus-dawn',
    description: 'A vibrant and refreshing scent that evokes the feeling of a sun-drenched morning in an orchard.',
    price: 150,
    image: 'https://saeedghani.pk/cdn/shop/files/Gush-Rush_300x.jpg?v=1750943026',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: {
      top: ['Bergamot', 'Grapefruit'],
      middle: ['Neroli', 'Petitgrain'],
      base: ['Vetiver', 'Amber'],
    },
    rating: 4.6,
    reviewCount: 98,
    reviews: [
      { id: '1', author: 'Sophia', rating: 5, title: 'Perfect for summer!', comment: 'So fresh and uplifting! It\'s like sunshine in a bottle. My go-to for warm weather.', date: '2023-08-05' },
    ]
  },
  {
    id: 3,
    name: 'Oud Mystique',
    slug: 'oud-mystique',
    description: 'A rich and opulent fragrance featuring rare oud wood, balanced with warm spices and precious resins.',
    price: 250,
    image: 'https://saeedghani.pk/cdn/shop/files/Sultan_300x.jpg?v=1750943031',
    category: 'Men',
    scentFamily: 'Woody',
    notes: {
      top: ['Saffron', 'Cardamom'],
      middle: ['Oud', 'Rose'],
      base: ['Amber', 'Patchouli', 'Vanilla'],
    },
    rating: 4.9,
    reviewCount: 210,
    reviews: [
       { id: '1', author: 'James', rating: 5, title: 'Masterpiece!', comment: 'The best oud fragrance I have ever smelled. It\'s powerful, complex, and incredibly luxurious. Worth every penny.', date: '2023-11-01' },
    ]
  },
  {
    id: 4,
    name: 'Velvet Amber',
    slug: 'velvet-amber',
    description: 'A warm, sensual, and comforting scent that wraps you in a soft blanket of amber and vanilla.',
    price: 190,
    image: 'https://saeedghani.pk/cdn/shop/files/Gush-Rush_300x.jpg?v=1750943026',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: {
      top: ['Pink Pepper', 'Bergamot'],
      middle: ['Labdanum', 'Cinnamon'],
      base: ['Amber', 'Tonka Bean', 'Benzoin'],
    },
    rating: 4.7,
    reviewCount: 155,
    reviews: []
  },
  {
    id: 5,
    name: 'Aqua Marine',
    slug: 'aqua-marine',
    description: 'A crisp and invigorating aquatic fragrance that captures the essence of a cool sea breeze on a summer day.',
    price: 160,
    image: 'https://saeedghani.pk/cdn/shop/files/imagination2_300x.jpg?v=1750943036',
    category: 'Men',
    scentFamily: 'Fresh',
    notes: {
      top: ['Sea Salt', 'Mint'],
      middle: ['Lavender', 'Geranium'],
      base: ['Driftwood', 'White Musk'],
    },
    rating: 4.5,
    reviewCount: 88,
    reviews: []
  },
  {
    id: 6,
    name: 'Rose Élégance',
    slug: 'rose-elegance',
    description: 'A modern and sophisticated take on a classic rose perfume, blending fresh rose petals with a hint of spice.',
    price: 200,
    image: 'https://saeedghani.pk/cdn/shop/files/Dark2_300x.jpg?v=1750943050',
    category: 'Women',
    scentFamily: 'Floral',
    notes: {
      top: ['Lychee', 'Peony'],
      middle: ['Rose de Mai', 'Magnolia'],
      base: ['Cedarwood', 'Honey'],
    },
    rating: 4.8,
    reviewCount: 132,
    reviews: []
  },
  {
    id: 7,
    name: 'Smoked Leather',
    slug: 'smoked-leather',
    description: 'A bold and confident fragrance with dominant notes of leather and smoke, reminiscent of a vintage library.',
    price: 220,
    image: 'https://saeedghani.pk/cdn/shop/files/212-men2_300x.jpg?v=1750943055',
    category: 'Men',
    scentFamily: 'Woody',
    notes: {
      top: ['Birch Tar', 'Black Pepper'],
      middle: ['Leather', 'Juniper'],
      base: ['Cade Oil', 'Vanilla', 'Sandalwood'],
    },
    rating: 4.9,
    reviewCount: 180,
    reviews: []
  },
  {
    id: 8,
    name: 'Orchid Noir',
    slug: 'orchid-noir',
    description: 'A mysterious and seductive oriental fragrance, centered around the exotic black orchid.',
    price: 210,
    image: 'https://saeedghani.pk/cdn/shop/files/Dark2_300x.jpg?v=1750943050',
    category: 'Women',
    scentFamily: 'Oriental',
    notes: {
      top: ['Black Truffle', 'Plum'],
      middle: ['Black Orchid', 'Spice'],
      base: ['Patchouli', 'Dark Chocolate', 'Incense'],
    },
    rating: 4.7,
    reviewCount: 165,
    reviews: []
  },
  {
    id: 9,
    name: 'Solar Flare',
    slug: 'solar-flare',
    description: 'A radiant burst of citrus and white florals, capturing the warmth of the sun.',
    price: 175,
    image: 'https://saeedghani.pk/cdn/shop/files/Cool-Water-new-box_300x.jpg?v=1750943054',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Mandarin', 'Lemon'], middle: ['Neroli', 'Jasmine'], base: ['Amber', 'Musk'] },
    rating: 4.6,
    reviewCount: 112,
    reviews: []
  },
  {
    id: 10,
    name: 'Emerald Woods',
    slug: 'emerald-woods',
    description: 'A deep, green fragrance reminiscent of a dense forest after rain.',
    price: 195,
    image: 'https://saeedghani.pk/cdn/shop/files/cigar_300x.jpg?v=1750943040',
    category: 'Men',
    scentFamily: 'Woody',
    notes: { top: ['Galbanum', 'Pine'], middle: ['Cedarwood', 'Moss'], base: ['Vetiver', 'Patchouli'] },
    rating: 4.8,
    reviewCount: 95,
    reviews: []
  },
  {
    id: 11,
    name: 'Peony Blush',
    slug: 'peony-blush',
    description: 'A delicate and romantic floral scent, soft as a blush on a cheek.',
    price: 165,
    image: 'https://saeedghani.pk/cdn/shop/files/Temptation_300x.jpg?v=1750943041',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Red Apple', 'Peony'], middle: ['Rose', 'Jasmine'], base: ['Suede', 'Musk'] },
    rating: 4.7,
    reviewCount: 140,
    reviews: []
  },
  {
    id: 12,
    name: 'Spice Bazaar',
    slug: 'spice-bazaar',
    description: 'An exotic and warm journey through a bustling spice market.',
    price: 230,
    image: 'https://saeedghani.pk/cdn/shop/files/Attar-2_24188ef1-0c05-47d0-8e16-5c3a26c0de57_300x.jpg?v=1750942879',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Cinnamon', 'Clove'], middle: ['Nutmeg', 'Ginger'], base: ['Vanilla', 'Tonka Bean'] },
    rating: 4.9,
    reviewCount: 201,
    reviews: []
  },
    {
    id: 13,
    name: 'Azure Coast',
    slug: 'azure-coast',
    description: 'A refreshing aquatic scent that transports you to the Mediterranean seaside.',
    price: 155,
    image: 'https://saeedghani.pk/cdn/shop/files/signature_300x.jpg?v=1750943042',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Sea Water', 'Cypress'], middle: ['Fig', 'Lavender'], base: ['Ambergris', 'Driftwood'] },
    rating: 4.6,
    reviewCount: 105,
    reviews: []
  },
  {
    id: 14,
    name: 'Crimson Oud',
    slug: 'crimson-oud',
    description: 'A passionate and intense fragrance combining the richness of oud with juicy red fruits.',
    price: 260,
    image: 'https://saeedghani.pk/cdn/shop/files/FinalAttarImage_300x.jpg?v=1750942831',
    category: 'Unisex',
    scentFamily: 'Woody',
    notes: { top: ['Raspberry', 'Saffron'], middle: ['Oud', 'Rose'], base: ['Leather', 'Amberwood'] },
    rating: 4.9,
    reviewCount: 189,
    reviews: []
  },
  {
    id: 15,
    name: 'Gardenia Veil',
    slug: 'gardenia-veil',
    description: 'A creamy, intoxicating white floral fragrance that is both elegant and timeless.',
    price: 185,
    image: 'https://saeedghani.pk/cdn/shop/files/fantasy_300x.jpg?v=1750943039',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Green Leaves', 'Pear'], middle: ['Gardenia', 'Tuberose'], base: ['Sandalwood', 'Musk'] },
    rating: 4.8,
    reviewCount: 120,
    reviews: []
  },
  {
    id: 16,
    name: 'Golden Sahara',
    slug: 'golden-sahara',
    description: 'A warm, resinous scent that evokes the heat of desert sands at sunset.',
    price: 215,
    image: 'https://saeedghani.pk/cdn/shop/files/Desire_300x.jpg?v=1750943028',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Incense', 'Myrrh'], middle: ['Labdanum', 'Benzoin'], base: ['Amber', 'Vanilla'] },
    rating: 4.7,
    reviewCount: 143,
    reviews: []
  },
  {
    id: 17,
    name: 'Silver Birch',
    slug: 'silver-birch',
    description: 'A crisp, clean, and modern woody scent with a cool, metallic edge.',
    price: 190,
    image: 'https://saeedghani.pk/cdn/shop/files/Untitled-1_1_300x.jpg?v=1750943025',
    category: 'Men',
    scentFamily: 'Woody',
    notes: { top: ['Bergamot', 'Cardamom'], middle: ['Birch', 'Lavender'], base: ['Vetiver', 'Musk'] },
    rating: 4.6,
    reviewCount: 110,
    reviews: []
  },
  {
    id: 18,
    name: 'Vanilla Sky',
    slug: 'vanilla-sky',
    description: 'A dreamy and comforting gourmand fragrance with a sophisticated, airy vanilla.',
    price: 170,
    image: 'https://saeedghani.pk/cdn/shop/files/Untitled-1_1_300x.jpg?v=1750943025',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Milk', 'Sugar'], middle: ['Vanilla Orchid', 'Heliotrope'], base: ['Bourbon Vanilla', 'Sandalwood'] },
    rating: 4.8,
    reviewCount: 198,
    reviews: []
  },
  {
    id: 19,
    name: 'Fico di Amalfi',
    slug: 'fico-di-amalfi',
    description: 'A vibrant scent capturing the essence of Italian fig groves.',
    price: 168,
    image: 'https://saeedghani.pk/cdn/shop/files/Sultan_300x.jpg?v=1750943031',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Fig Nectar', 'Bergamot'], middle: ['Fig Leaf', 'Jasmine'], base: ['Cedarwood', 'Musk'] },
    rating: 4.7,
    reviewCount: 135,
    reviews: []
  },
  {
    id: 20,
    name: 'Black Vetiver',
    slug: 'black-vetiver',
    description: 'A dark, earthy, and smoky vetiver fragrance for the confident individual.',
    price: 205,
    image: 'https://saeedghani.pk/cdn/shop/files/Fate_50ml_Box_300x.jpg?v=1750942974',
    category: 'Men',
    scentFamily: 'Woody',
    notes: { top: ['Grapefruit', 'Pepper'], middle: ['Vetiver', 'Incense'], base: ['Patchouli', 'Oakmoss'] },
    rating: 4.9,
    reviewCount: 178,
    reviews: []
  },
  {
    id: 21,
    name: 'Cherry Blossom',
    slug: 'cherry-blossom',
    description: 'A light, airy, and ethereal floral celebrating the beauty of spring.',
    price: 150,
    image: 'https://saeedghani.pk/cdn/shop/files/Prime_50ml_Box_300x.jpg?v=1750942977',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Sakura Blossom', 'Nashi Pear'], middle: ['Rose', 'Mimosa'], base: ['White Musk', 'Sandalwood'] },
    rating: 4.6,
    reviewCount: 122,
    reviews: []
  },
  {
    id: 22,
    name: 'Tonka Imperiale',
    slug: 'tonka-imperiale',
    description: 'A majestic and addictive oriental scent built around the rich Tonka bean.',
    price: 240,
    image: 'https://saeedghani.pk/cdn/shop/files/Sacred_50ml_Box_300x.jpg?v=1750942976',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Almond', 'Rosemary'], middle: ['Tonka Bean', 'Tobacco'], base: ['Amber', 'Incense'] },
    rating: 4.9,
    reviewCount: 220,
    reviews: []
  },
  {
    id: 23,
    name: 'Green Tea Therapy',
    slug: 'green-tea-therapy',
    description: 'A calming and zen-like fragrance that revitalizes the senses.',
    price: 135,
    image: 'https://saeedghani.pk/cdn/shop/files/Sacred_50ml_Box_300x.jpg?v=1750942976',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Green Tea', 'Lemon'], middle: ['Mint', 'Jasmine'], base: ['Musk', 'Celery Seed'] },
    rating: 4.5,
    reviewCount: 102,
    reviews: []
  },
  {
    id: 24,
    name: 'Sandalwood Sacre',
    slug: 'sandalwood-sacre',
    description: 'A creamy, spiritual, and meditative sandalwood fragrance.',
    price: 225,
    image: 'https://saeedghani.pk/cdn/shop/files/Ivory_50ml_Box_300x.jpg?v=1750942975',
    category: 'Unisex',
    scentFamily: 'Woody',
    notes: { top: ['Cardamom', 'Violet'], middle: ['Mysore Sandalwood', 'Papyrus'], base: ['Cedarwood', 'Amber'] },
    rating: 4.8,
    reviewCount: 185,
    reviews: []
  },
  {
    id: 25,
    name: 'Lily of the Valley',
    slug: 'lily-of-the-valley',
    description: 'A pure, green, and innocent floral capturing the dewy freshness of May bells.',
    price: 160,
    image: 'https://saeedghani.pk/cdn/shop/files/Aqua_300x.jpg?v=1750943029',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Green Notes', 'Bergamot'], middle: ['Lily-of-the-Valley', 'Jasmine'], base: ['White Musk', 'Oakmoss'] },
    rating: 4.7,
    reviewCount: 115,
    reviews: []
  },
  {
    id: 26,
    name: 'Amber Absolute',
    slug: 'amber-absolute',
    description: 'An uncompromisingly rich and dense amber fragrance with a touch of smoke.',
    price: 270,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/amber-absolu-1.jpg',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Incense', 'Amber'], middle: ['Labdanum', 'Vanilla'], base: ['Sandalwood', 'Patchouli'] },
    rating: 4.9,
    reviewCount: 230,
    reviews: []
  },
  {
    id: 27,
    name: 'Neroli Portofino',
    slug: 'neroli-portofino',
    description: 'A sparkling and effervescent citrus floral that captures the Italian Riviera.',
    price: 180,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/10/NEROLI-PORTOFINO-1.jpg',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Neroli', 'Bergamot'], middle: ['Orange Blossom', 'Lavender'], base: ['Amber', 'Musk Mallow'] },
    rating: 4.7,
    reviewCount: 160,
    reviews: []
  },
  {
    id: 28,
    name: 'Vetiver Veritas',
    slug: 'vetiver-veritas',
    description: 'A true, raw, and multifaceted vetiver, from green roots to smoky earth.',
    price: 210,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/teree-dhermes-1.jpg',
    category: 'Men',
    scentFamily: 'Woody',
    notes: { top: ['Grapefruit', 'Lime'], middle: ['Haitian Vetiver', 'Java Vetiver'], base: ['Oakmoss', 'Ambergris'] },
    rating: 4.8,
    reviewCount: 155,
    reviews: []
  },
  {
    id: 29,
    name: 'Jasmin Rouge',
    slug: 'jasmin-rouge',
    description: 'A voluptuous and spicy floral fragrance that is unabashedly seductive.',
    price: 235,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/10/JASMIN-ROUGE-1.jpg',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Cinnamon', 'Ginger'], middle: ['Jasmine Sambac', 'Ylang-Ylang'], base: ['Vanilla', 'Leather'] },
    rating: 4.8,
    reviewCount: 190,
    reviews: []
  },
  {
    id: 30,
    name: 'Tobacco Vanille',
    slug: 'tobacco-vanille',
    description: 'A rich and opulent blend of tobacco leaf, vanilla, and spices.',
    price: 255,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/10/TOBACCO-VANILLE-1.jpg',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Tobacco Leaf', 'Spices'], middle: ['Tonka Bean', 'Tobacco Blossom'], base: ['Dried Fruits', 'Vanilla'] },
    rating: 4.9,
    reviewCount: 305,
    reviews: []
  },
  {
    id: 31,
    name: 'Elysian Fields',
    slug: 'elysian-fields',
    description: 'A serene and aromatic fragrance with notes of lavender and hay.',
    price: 175,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/aventus-creed-1.jpg',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Lavender', 'Clary Sage'], middle: ['Hay', 'Tonka Bean'], base: ['Oakmoss', 'Musk'] },
    rating: 4.6,
    reviewCount: 99,
    reviews: []
  },
  {
    id: 32,
    name: 'Cedar Atlas',
    slug: 'cedar-atlas',
    description: 'A dry, majestic, and slightly sweet cedarwood fragrance.',
    price: 195,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Bleu-de-chanel-for-men-1.jpg',
    category: 'Men',
    scentFamily: 'Woody',
    notes: { top: ['Black Pepper', 'Juniper Berry'], middle: ['Atlas Cedarwood', 'Virginia Cedarwood'], base: ['Sandalwood', 'Vetiver'] },
    rating: 4.7,
    reviewCount: 130,
    reviews: []
  },
  {
    id: 33,
    name: 'Fleur d\'Oranger',
    slug: 'fleur-doranger',
    description: 'A radiant and sunny orange blossom scent that is pure joy in a bottle.',
    price: 185,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Jadore-for-women-by-dior-1.jpg',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Petitgrain', 'Bergamot'], middle: ['Orange Blossom', 'Neroli'], base: ['Musk', 'Honey'] },
    rating: 4.8,
    reviewCount: 140,
    reviews: []
  },
  {
    id: 34,
    name: 'Incense Rosé',
    slug: 'incense-rose',
    description: 'A mystical and spiritual blend of church incense and deep red rose.',
    price: 245,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/rose-dmalfi-1.jpg',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Frankincense', 'Myrrh'], middle: ['Taif Rose', 'Cardamom'], base: ['Oud', 'Sandalwood'] },
    rating: 4.9,
    reviewCount: 195,
    reviews: []
  },
  {
    id: 35,
    name: 'Aqua Celestia',
    slug: 'aqua-celestia',
    description: 'A heavenly cool and clean musk with a touch of mint and lime.',
    price: 165,
    image: 'https://saeedghani.pk/cdn/shop/files/Artboard1_57262f27-0b16-4191-8451-9bd65a6f02a6.jpg?v=1716378601',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Lime', 'Mint'], middle: ['Blackcurrant', 'Mimosa'], base: ['White Musk', 'Rose'] },
    rating: 4.6,
    reviewCount: 125,
    reviews: []
  },
  {
    id: 36,
    name: 'Sycomore',
    slug: 'sycomore',
    description: 'A noble and smoky vetiver with a hint of cypress and tobacco.',
    price: 280,
    image: 'https://saeedghani.pk/cdn/shop/files/Untitled-1_d0c3c6f4-b251-4e78-90f7-11110022d427.jpg?v=1716378415',
    category: 'Unisex',
    scentFamily: 'Woody',
    notes: { top: ['Vetiver', 'Cypress'], middle: ['Juniper', 'Spices'], base: ['Sandalwood', 'Tobacco'] },
    rating: 4.9,
    reviewCount: 210,
    reviews: []
  },
  {
    id: 37,
    name: 'Carnal Flower',
    slug: 'carnal-flower',
    description: 'The most realistic and potent tuberose fragrance, green and indolic.',
    price: 295,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/My-way-giorgio-armani-for-women-1.jpg',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Eucalyptus', 'Melon'], middle: ['Tuberose', 'Ylang-Ylang'], base: ['Coconut', 'White Musk'] },
    rating: 4.8,
    reviewCount: 225,
    reviews: []
  },
  {
    id: 38,
    name: 'Noir Epices',
    slug: 'noir-epices',
    description: 'A dark and mysterious spicy oriental with a prominent geranium note.',
    price: 230,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/black-xs-1.jpg',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Orange', 'Geranium'], middle: ['Clove', 'Nutmeg', 'Pepper'], base: ['Sandalwood', 'Patchouli'] },
    rating: 4.8,
    reviewCount: 180,
    reviews: []
  },
  {
    id: 39,
    name: 'Mojave Ghost',
    slug: 'mojave-ghost',
    description: 'A woody and ethereal scent inspired by the ghost flower of the Mojave Desert.',
    price: 210,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/07/2-15.jpg',
    category: 'Unisex',
    scentFamily: 'Woody',
    notes: { top: ['Ambrette', 'Sapodilla'], middle: ['Violet', 'Sandalwood'], base: ['Amber', 'Cedarwood'] },
    rating: 4.7,
    reviewCount: 240,
    reviews: []
  },
  {
    id: 40,
    name: 'Philosykos',
    slug: 'philosykos',
    description: 'An ode to the fig tree: the leaves, the wood, the fruit.',
    price: 180,
    image: 'https://saeedghani.pk/cdn/shop/files/Artboard1_468c8b41-3ef5-420d-9b5a-47101894d356.jpg?v=1716378586',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Fig Leaf', 'Fig'], middle: ['Coconut', 'Green Notes'], base: ['Cedar', 'Fig Tree'] },
    rating: 4.8,
    reviewCount: 200,
    reviews: []
  },
  {
    id: 41,
    name: 'La Tulipe',
    slug: 'la-tulipe',
    description: 'A fresh, clean, and optimistic floral capturing the idea of a tulip.',
    price: 190,
    image: 'https://saeedghani.pk/cdn/shop/files/Untitled-1_6f406858-a590-449e-876a-54378f413340.jpg?v=1716378440',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Rhubarb', 'Cyclamen'], middle: ['Tulip'], base: ['Blond Woods', 'Vetiver'] },
    rating: 4.7,
    reviewCount: 150,
    reviews: []
  },
  {
    id: 42,
    name: 'Musc Ravageur',
    slug: 'musc-ravageur',
    description: 'A sensual and powerful amber musk that is both sophisticated and raw.',
    price: 250,
    image: 'https://saeedghani.pk/cdn/shop/files/01_1_3e71d374-13eb-46f3-94c9-166258c7041a.jpg?v=1697274061',
    category: 'Unisex',
    scentFamily: 'Oriental',
    notes: { top: ['Bergamot', 'Tangerine'], middle: ['Cinnamon', 'Clove'], base: ['Musk', 'Vanilla', 'Amber'] },
    rating: 4.9,
    reviewCount: 260,
    reviews: []
  },
  {
    id: 43,
    name: 'Royal Oud',
    slug: 'royal-oud',
    description: 'A stylish and warm fougère with a beautiful balance of wood and spice.',
    price: 320,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/creed-royal-oud-1.jpg',
    category: 'Men',
    scentFamily: 'Woody',
    notes: { top: ['Pink Pepper', 'Lemon'], middle: ['Cedar', 'Angelica'], base: ['Oud', 'Sandalwood', 'Musk'] },
    rating: 4.9,
    reviewCount: 280,
    reviews: []
  },
  {
    id: 44,
    name: 'Aventus',
    slug: 'aventus',
    description: 'A legendary fragrance celebrating strength, power, and success.',
    price: 350,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2021/08/aventus-creed-1.jpg',
    category: 'Men',
    scentFamily: 'Fresh',
    notes: { top: ['Pineapple', 'Bergamot'], middle: ['Birch', 'Rose'], base: ['Oakmoss', 'Ambergris'] },
    rating: 4.9,
    reviewCount: 550,
    reviews: []
  },
  {
    id: 45,
    name: 'Delina',
    slug: 'delina',
    description: 'A modern floral bouquet dominated by Turkish rose, lily of the valley and peony.',
    price: 290,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Delina-parfums-de-marly-for-women-1.jpg',
    category: 'Women',
    scentFamily: 'Floral',
    notes: { top: ['Lychee', 'Rhubarb'], middle: ['Turkish Rose', 'Peony'], base: ['Cashmeran', 'Vetiver'] },
    rating: 4.8,
    reviewCount: 310,
    reviews: []
  },
  {
    id: 46,
    name: 'Herod',
    slug: 'herod',
    description: 'A regal and smoky tobacco fragrance with a gourmand twist.',
    price: 260,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Herod-parfums-de-marly-for-men-1.jpg',
    category: 'Men',
    scentFamily: 'Oriental',
    notes: { top: ['Cinnamon', 'Pepperwood'], middle: ['Tobacco Leaf', 'Incense'], base: ['Vanilla', 'Cedar'] },
    rating: 4.8,
    reviewCount: 240,
    reviews: []
  },
  {
    id: 47,
    name: 'Santal 33',
    slug: 'santal-33',
    description: 'An iconic, intoxicating aroma of smoke, leather, and Australian sandalwood.',
    price: 285,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Santal-33-le-labo-unisex-1.jpg',
    category: 'Unisex',
    scentFamily: 'Woody',
    notes: { top: ['Cardamom', 'Violet Accord'], middle: ['Iris', 'Ambrox'], base: ['Sandalwood', 'Cedarwood', 'Leather'] },
    rating: 4.7,
    reviewCount: 450,
    reviews: []
  },
  {
    id: 48,
    name: 'Virgin Island Water',
    slug: 'virgin-island-water',
    description: 'A tropical cocktail of coconut, lime, and white rum.',
    price: 240,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Creed-virgin-island-water-unisex-1.jpg',
    category: 'Unisex',
    scentFamily: 'Fresh',
    notes: { top: ['Lime', 'Coconut'], middle: ['Jasmine', 'Ylang-Ylang'], base: ['Sugar Cane', 'White Rum'] },
    rating: 4.7,
    reviewCount: 220,
    reviews: []
  },
  {
    id: 49,
    name: 'Portrait of a Lady',
    slug: 'portrait-of-a-lady',
    description: 'An elegant, opulent, and dramatic oriental rose fragrance.',
    price: 330,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Portrait-of-a-lady-frederic-malle-for-women-1.jpg',
    category: 'Women',
    scentFamily: 'Oriental',
    notes: { top: ['Rose', 'Clove'], middle: ['Patchouli', 'Sandalwood'], base: ['Frankincense', 'Amber'] },
    rating: 4.9,
    reviewCount: 350,
    reviews: []
  },
  {
    id: 50,
    name: 'Tam Dao',
    slug: 'tam-dao',
    description: 'A tribute to the sacred sandalwood of the holy forests of Indochina.',
    price: 195,
    image: 'https://perfumehut.com.pk/wp-content/uploads/2023/12/Tam-dao-diptyque-unisex-1.jpg',
    category: 'Unisex',
    scentFamily: 'Woody',
    notes: { top: ['Cypress', 'Myrtle'], middle: ['Sandalwood', 'Cedar'], base: ['Ambergris', 'Spices'] },
    rating: 4.8,
    reviewCount: 190,
    reviews: []
  },
];

export function getProducts(): Product[] {
  return products;
}

export function getProductBySlug(slug: string): Product | undefined {
  const product = products.find((p) => p.slug === slug);
  return product;
}

export function getProductById(id: number): Product | undefined {
   const product = products.find((p) => p.id === id);
   return product;
}

    